spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/job_scheduler
    username: adeshsengar
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  quartz:
    job-store-type: memory

server:
  port: 8080

jakarta:
  persistence:
    jdbc:
      url: ${spring.datasource.url}
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui/
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    com.scheduler: DEBUG
    org.springframework.web: INFO
    org.quartz: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
